### PR TITLE
Added rebalance proposal refresh

### PR DESCRIPTION
**Pull request by ppatierno**
### Type of change

- Enhancement / new feature

### Description

Added the possibility to "refresh" a rebalance proposal so actually asking for a new rebalance proposal from the `ProposalReady` state.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Update/write design documentation in `./design`
- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by ppatierno** [comment]
@tomncooper @kyguy it's really a simple fix about enabling the user to "refresh" an already ready rebalance proposal. Anyway, I think that it's quite the same (even at code level) as when the state machine is in the "Stopped" state and the user can do a "restart" moving to "PendingProposal" again so actually asking for a rebalance proposal. Maybe we can just use one annotation for that an not having "restart" (if from "Stopped" state) and "refresh" (if from "ProposalReady" state) but I cannot think of a good annotation name which could make sense for both. Or we can just stay with two different annotations values.

**Comment by tomncooper** [comment]
I think we should have one "refresh" annotation, as they both do the same thing, they cause a new proposal to be retrieved and eventually lead to the `ProposalReady` state waiting for approval.

**Comment by ppatierno** [comment]
What sounds strange to me is doing a "refresh" from a "Stopped" state (instead of a "restart").

**Comment by tomncooper** [comment]
Well I suppose there is a semantic difference but you can "refresh" a stale or paused thing so I still think it is ok. It is one less moving part but I happy to have both.

**Review by tomncooper — APPROVED** [review]

**Comment by ppatierno** [comment]
I have really no strong opinion on that :(

**Review by kyguy — APPROVED** [review]
I think one `refresh` annotation would work nicely for `refresh` and `restart` but I don't mind having both

**Comment by ppatierno** [comment]
Let's go for "refresh" for both then!

**Pull request merged**
